#! /bin/python

import sys

if len(sys.argv) < 1:
    print("Input file expected", file=sys.stderr)
    sys.exit(1)


# need to load full file this round
with open(sys.argv[1]) as infile:
    costs = [int(line.strip()) for line in infile]

    for i in range(len(costs)):
        for j in range(i+1, len(costs)):
            match = 2020 - costs[i] - costs[j]
            if match in costs:
                print(f"Found! {costs[i]} + {costs[j]} + {match} = 2020")
                print(f"Result is {costs[i] * costs[j] * match}")
                sys.exit(0)

    else:
        print("Did not find anything...")
