#! /bin/python

import sys

if len(sys.argv) < 1:
    print("Input file expected", file=sys.stderr)
    sys.exit(1)


with open(sys.argv[1]) as infile:

    # dictionary of dictionaries
    instructions = []
    for instruction in infile.readlines():
        instruction = instruction.split()
        instructions.append((instruction[0], int(instruction[1])))

    visited = set()
    acc = 0
    i = 0
    while i < len(instructions):
        if i in visited:
            print(f"Operation {i} ({instructions[i]}) already visited")
            break

        visited.add(i)
        if instructions[i][0] == "acc":
            acc += instructions[i][1]
            i += 1
        elif instructions[i][0] == "jmp":
            i += instructions[i][1]
        else:
            i += 1

    print(f"The accumulator is at {acc}")
